const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function runSeed() {
  if (!process.env.DATABASE_URL) {
    console.log("No DATABASE_URL set, skipping seed.");
    return;
  }
  console.log("🌱 Checking database state for SMK Telkom Malang XI Internasional...");

  try {
    // 1. Class Profile
    const profileCount = await prisma.classProfile.count();
    if (profileCount === 0) {
      console.log("Creating default ClassProfile in PostgreSQL...");
      await prisma.classProfile.create({
        data: {
          id: "default",
          name: "XI Internasional",
          generation: "Angkatan 2026",
          school: "SMK Telkom Malang",
          tagline: "Connected. Forward. Together.",
          description:
            "Pusat identitas, dokumentasi, komunikasi, showcase, dan portofolio kelas yang dibangun dengan standar produk digital modern.",
          homeroomTeacher: "Andree Rivan Kurniawan, M.Pd",
          classPresident: "Radisty Dhisa Aqila",
          vicePresident: "Elang Dimas Syadewa",
          memberCount: 25,
          projectCount: 24,
          achievementCount: 15,
          eventCount: 18,
          labLocation: "Ruang 34, SMK Telkom Malang, Jl. Danau Ranau, Sawojajar, Kota Malang",
          email: "contact@internext.web.id",
          instagram: "https://instagram.com/internext.class",
          github: "https://github.com/internext-class",
          youtube: "https://youtube.com/@internext",
          tiktok: "https://tiktok.com/@internext.class",
        },
      });
    }

    // 2. Chat Channels
    const channels = [
      {
        id: "apresiasi-publik",
        name: "apresiasi-publik",
        title: "Kanal Apresiasi & Buku Tamu",
        topic: "Ruang apresiasi, doa, dan motivasi bagi siswa XI Internasional SMK Telkom Malang. Bot menyambut setiap ucapan hangat!",
        badge: "Utama",
        orderIndex: 0,
      },
      {
        id: "ngobrol-santai",
        name: "ngobrol-santai",
        title: "Obrolan Santai Siswa & Tamu",
        topic: "Kanal obrolan bebas antar siswa, alumni, dan teman-teman tanpa bot. Mengalir bebas untuk berdiskusi santai!",
        badge: "Komunitas",
        orderIndex: 1,
      },
      {
        id: "tanya-pengurus",
        name: "tanya-pengurus",
        title: "Tanya & Kontak Pengurus",
        topic: "Saluran komunikasi langsung dengan ketua kelas, wali kelas, dan tim pengurus XI Internasional.",
        badge: "Resmi",
        orderIndex: 2,
      },
      {
        id: "kolaborasi-proyek",
        name: "kolaborasi-proyek",
        title: "Kolaborasi & Ide Tech",
        topic: "Eksplorasi ide aplikasi, open source, persiapan LKS, dan kerja sama teknologi bareng siswa Moklet.",
        badge: "Tech",
        orderIndex: 3,
      },
    ];

    for (const ch of channels) {
      await prisma.chatChannel.upsert({
        where: { id: ch.id },
        update: {},
        create: ch,
      });
    }

    // 3. Initial Chat Messages
    const chatCount = await prisma.chatMessage.count();
    if (chatCount === 0) {
      const initialChat = [
        {
          id: "chat-apresiasi-1",
          channelId: "apresiasi-publik",
          name: "Andree Rivan Kurniawan, M.Pd",
          role: "Guru",
          message: "Bangga melihat dedikasi dan karya hebat anak-anak XI Internasional SMK Telkom Malang. Teruslah berkarya dan jadilah engineer berintegritas tinggi!",
          timestamp: "10 Feb 2026, 10:00",
          reactions: [{ emoji: "❤️", count: 24, userReacted: false }, { emoji: "👏", count: 16, userReacted: false }],
        },
        {
          id: "chat-apresiasi-2",
          channelId: "apresiasi-publik",
          name: "Kevin Pratama, S.Kom (Alumni Moklet)",
          role: "Alumni",
          message: "Website kelasnya luar biasa keren! Nuansa dark mode dan portofolio 360-nya serasa tech startup silicon valley. Keren banget adik-adik XI Internasional!",
          timestamp: "14 Feb 2026, 14:30",
          reactions: [{ emoji: "🔥", count: 19, userReacted: false }, { emoji: "🚀", count: 11, userReacted: false }],
        },
        {
          id: "chat-santai-1",
          channelId: "ngobrol-santai",
          name: "Radisty Dhisa Aqila",
          role: "Siswa",
          message: "Halo semuanya! Selamat datang di kanal ngobrol santai XI Internasional. Di sini bebas ngobrol santai seputar projek, sharing ilmu, atau sekadar sapa-sapaan! ☕👋",
          timestamp: "Hari ini, 09:00",
          reactions: [{ emoji: "🚀", count: 8, userReacted: false }],
        },
      ];

      for (const m of initialChat) {
        await prisma.chatMessage.upsert({
          where: { id: m.id },
          update: {},
          create: m,
        });
      }
    }

    // 4. Members (25 Students)
    console.log("Syncing 25 official students of XI Internasional into database...");
    const students = [
        {
          id: "m-1",
          name: "Aryasatya Athallah",
          nickname: "Arya",
          role: "Anggota",
          department: "Frontend & Cloud",
          quote: "Belajar terus, eksplorasi tanpa batas.",
          bio: "Siswa XI Internasional SMK Telkom Malang dengan fokus antarmuka web modern, React, dan integrasi cloud.",
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
          skills: ["React", "Next.js", "Tailwind CSS", "Cloud Basics"],
          githubUrl: "https://github.com",
          linkedinUrl: "https://linkedin.com",
          instagramUrl: "https://instagram.com",
          isManagement: false,
          orderIndex: 1,
        },
        {
          id: "m-2",
          name: "Azkya Rahma Azzahra",
          nickname: "Azkya",
          role: "Anggota",
          department: "UI/UX & Mobile Design",
          quote: "Desain yang bermakna lahir dari empati mendalam.",
          bio: "Merancang wireframe, user flow, dan antarmuka aplikasi interaktif dengan pendekatan human-centered design.",
          avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=faces",
          skills: ["Figma", "UI/UX Design", "Wireframing", "User Research"],
          instagramUrl: "https://instagram.com",
          linkedinUrl: "https://linkedin.com",
          isManagement: false,
          orderIndex: 2,
        },
        {
          id: "m-3",
          name: "Berlian Alshani Raffisya",
          nickname: "Berlian",
          role: "Bendahara 1",
          department: "Finance & Administration",
          quote: "Transparansi dan ketelitian adalah pondasi integritas.",
          bio: "Mengelola pembukuan kas kelas, alokasi budget kegiatan angkatan, dan transparansi laporan keuangan XI Internasional.",
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=faces",
          skills: ["Financial Management", "Budgeting", "Spreadsheets", "Accountability"],
          instagramUrl: "https://instagram.com",
          linkedinUrl: "https://linkedin.com",
          isManagement: true,
          orderIndex: 3,
        },
        {
          id: "m-4",
          name: "Daffa Fakhrizzal Nauvan Esa Arzany",
          nickname: "Daffa",
          role: "Anggota",
          department: "Fullstack Web & Systems",
          quote: "Kode yang bersih adalah cerminan pikiran yang teratur.",
          bio: "Pengembang fullstack berorientasi pada clean code, arsitektur REST API, dan optimalisasi basis data.",
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces",
          skills: ["Node.js", "Express", "TypeScript", "PostgreSQL"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 4,
        },
        {
          id: "m-5",
          name: "Elang Dimas Syadewa",
          nickname: "Elang",
          role: "Wakil Ketua Kelas",
          department: "Operations & Product",
          quote: "Kreativitas dan disiplin adalah dua sisi dari koin yang sama.",
          bio: "Wakil ketua kelas XI Internasional SMK Telkom Malang. Mengawal koordinasi tim teknis, operasional divisi, dan sistem desain kelas.",
          avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces",
          skills: ["Project Management", "UI/UX", "Product Strategy", "Team Operations"],
          githubUrl: "https://github.com",
          linkedinUrl: "https://linkedin.com",
          instagramUrl: "https://instagram.com",
          isManagement: true,
          orderIndex: 5,
        },
        {
          id: "m-6",
          name: "Fatih Lintang Adzahabi",
          nickname: "Fatih",
          role: "Sekretaris 2",
          department: "Documentation & Strategy",
          quote: "Dokumentasi yang rapi menghasilkan eksekusi yang terarah.",
          bio: "Mengelola arsip data, notulensi rapat tim pengurus, dan dokumentasi kemajuan project digital kelas XI Internasional.",
          avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=faces",
          skills: ["Technical Documentation", "Notion", "Markdown", "Public Relations"],
          githubUrl: "https://github.com",
          isManagement: true,
          orderIndex: 6,
        },
        {
          id: "m-7",
          name: "Gerardus Cannavaro",
          nickname: "Gerard",
          role: "Anggota",
          department: "Cyber Security & Networks",
          quote: "Keamanan adalah proses berkesinambungan, bukan tujuan akhir.",
          bio: "Mendalami network pentesting, hardening server, zero-trust architecture, dan keamanan sistem komputer.",
          avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
          skills: ["Network Security", "Linux", "Python", "Penetration Testing"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 7,
        },
        {
          id: "m-8",
          name: "Kenzie Abqary Nararya",
          nickname: "Kenzie",
          role: "Anggota",
          department: "Game Dev & 3D Interactive",
          quote: "Interaktivitas mengubah imajinasi menjadi pengalaman nyata.",
          bio: "Spesialis gameplay programming, visual scripting, dan perancangan asset 3D interaktif pada engine modern.",
          avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=faces",
          skills: ["Godot", "C#", "Blender", "3D Modeling"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 8,
        },
        {
          id: "m-9",
          name: "Keyza Permata Safira Ramadhani",
          nickname: "Keyza",
          role: "Anggota",
          department: "Creative Media & Branding",
          quote: "Visual yang kuat menyampaikan ribuan cerita tanpa kata.",
          bio: "Mengembangkan materi promosi, visual branding kelas, motion graphic, dan konten publikasi digital angkatan.",
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
          skills: ["Illustrator", "Motion Graphics", "Branding", "Content Creation"],
          instagramUrl: "https://instagram.com",
          isManagement: false,
          orderIndex: 9,
        },
        {
          id: "m-10",
          name: "Keola Mahatma Kayana Al Akbar",
          nickname: "Keola",
          role: "Anggota",
          department: "Backend & Distributed Systems",
          quote: "Arsitektur tangguh menopang skalabilitas tanpa kompromi.",
          bio: "Pengembang sistem backend berbasis microservices, message queues, dan perancangan database terdistribusi.",
          avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&crop=faces",
          skills: ["Golang", "PostgreSQL", "Docker", "Redis"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 10,
        },
        {
          id: "m-11",
          name: "Leonard Owen Handy Hartanto",
          nickname: "Owen",
          role: "Anggota",
          department: "Software Engineering",
          quote: "Konsistensi kecil setiap hari menghasilkan lompatan inovasi besar.",
          bio: "Software developer dengan antusiasme tinggi pada TypeScript, clean architecture, dan pipeline automated testing.",
          avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=faces",
          skills: ["TypeScript", "React", "Jest", "Algorithms"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 11,
        },
        {
          id: "m-12",
          name: "M. Affan Daib",
          nickname: "Affan",
          role: "Anggota",
          department: "Embedded Systems & IoT",
          quote: "Menghubungkan dunia fisik dengan kecerdasan digital.",
          bio: "Eksplorasi mikrokontroler ESP32, arsitektur sensor pintar, protokol MQTT, dan monitoring telemetry cloud.",
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces",
          skills: ["C++", "ESP32", "MQTT", "Hardware Prototyping"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 12,
        },
        {
          id: "m-13",
          name: "Naurah Lubnaa Syeima Masarrah",
          nickname: "Naurah",
          role: "Anggota",
          department: "Data Science & AI Research",
          quote: "Data adalah kompas penunjuk arah keputusan masa depan.",
          bio: "Mendalami machine learning, visualisasi analitik data, dan pemanfaatan Large Language Models untuk automasi.",
          avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces",
          skills: ["Python", "Pandas", "Scikit-Learn", "Data Analytics"],
          linkedinUrl: "https://linkedin.com",
          isManagement: false,
          orderIndex: 13,
        },
        {
          id: "m-14",
          name: "Okka Adelard Syahbarr",
          nickname: "Okka",
          role: "Anggota",
          department: "DevOps & Cloud Infrastructure",
          quote: "Automate everything, ship with confidence.",
          bio: "Pengelolaan server homelab, kontainerisasi Docker, CI/CD GitHub Actions, dan monitoring performa web.",
          avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=faces",
          skills: ["Docker", "Linux", "GitHub Actions", "Nginx"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 14,
        },
        {
          id: "m-15",
          name: "Pargata Halu Taraka",
          nickname: "Pargata",
          role: "Anggota",
          department: "Mobile Applications",
          quote: "Setiap interaksi pengguna harus terasa cepat, responsif, dan intuitif.",
          bio: "Pengembang aplikasi multiplatform Flutter dengan fokus pada responsivitas UI dan state management modern.",
          avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
          skills: ["Flutter", "Dart", "Firebase", "State Management"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 15,
        },
        {
          id: "m-16",
          name: "Prabu Panedya Firdaus Putra Aglar",
          nickname: "Prabu",
          role: "Anggota",
          department: "System Architecture & Cloud",
          quote: "Membangun dengan standar industri sedari dini.",
          bio: "Mendalami arsitektur cloud serverless, micro-frontend, dan integrasi backend berkecepatan tinggi.",
          avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=faces",
          skills: ["Next.js", "Serverless", "Node.js", "PostgreSQL"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 16,
        },
        {
          id: "m-17",
          name: "Prama Javas Aryatama",
          nickname: "Javas",
          role: "Anggota",
          department: "Web Performance & Optimization",
          quote: "Kecepatan adalah fitur terbaik aplikasi modern.",
          bio: "Spesialis optimasi Core Web Vitals, asset caching, bundle splitting, dan pengalaman browsing ultra cepat.",
          avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces",
          skills: ["Web Vitals", "Lighthouse", "Performance Tuning", "JavaScript"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 17,
        },
        {
          id: "m-18",
          name: "Radisty Kirana Dhisa Aqila",
          nickname: "Dhisa",
          role: "Ketua Kelas",
          department: "Executive Leadership & Fullstack",
          quote: "Membangun masa depan bukan tentang menunggu, tapi mengeksekusi.",
          bio: "Ketua kelas XI Internasional SMK Telkom Malang. Tech lead dan koordinator platform digital Internext, memimpin 25 talenta digital Moklet.",
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
          skills: ["TypeScript", "Next.js", "Agile Leadership", "Fullstack Development"],
          githubUrl: "https://github.com",
          linkedinUrl: "https://linkedin.com",
          instagramUrl: "https://instagram.com",
          isManagement: true,
          orderIndex: 18,
        },
        {
          id: "m-19",
          name: "Raihan Bagas Kriskayana",
          nickname: "Raihan",
          role: "Anggota",
          department: "Interactive UI & Motion",
          quote: "Animasi yang halus menghidupkan pengalaman web.",
          bio: "Spesialis motion web dengan GSAP, Framer Motion, micro-interactions, dan layout modern.",
          avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&crop=faces",
          skills: ["GSAP", "Framer Motion", "CSS Art", "UI Design"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 19,
        },
        {
          id: "m-20",
          name: "Razan Wira Aryanta",
          nickname: "Razan",
          role: "Anggota",
          department: "QA & Automated Testing",
          quote: "Kualitas kode dibangun dengan standar kedisiplinan tinggi.",
          bio: "Fokus pada pengujian otomatis web end-to-end menggunakan Playwright, integration testing, dan continuous regression testing.",
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces",
          skills: ["Playwright", "Test Automation", "Debugging", "CI/CD"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 20,
        },
        {
          id: "m-21",
          name: "Reza Al Fath Fadhilah",
          nickname: "Reza",
          role: "Anggota",
          department: "Machine Learning & Backend",
          quote: "Eksplorasi kecerdasan buatan untuk pemecahan masalah nyata.",
          bio: "Membangun model machine learning terintegrasi API web untuk klasifikasi dan pengenalan pola cerdas.",
          avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=faces",
          skills: ["Python", "FastAPI", "TensorFlow", "PostgreSQL"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 21,
        },
        {
          id: "m-22",
          name: "Tazkia Adila Affandie",
          nickname: "Tazkia",
          role: "Anggota",
          department: "Product Management & Research",
          quote: "Pahami masalah pengguna, maka solusi terbaik akan mengikuti.",
          bio: "Riset kebutuhan pengguna produk, evaluasi usability, dan perancangan roadmap fitur aplikasi angkatan.",
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
          skills: ["Product Research", "User Journey", "Analytics", "Wireframing"],
          linkedinUrl: "https://linkedin.com",
          isManagement: false,
          orderIndex: 22,
        },
        {
          id: "m-23",
          name: "Tetra Ezar Putratoro",
          nickname: "Tetra",
          role: "Anggota",
          department: "Database & Storage Systems",
          quote: "Integritas data adalah fondasi kokoh setiap aplikasi.",
          bio: "Fokus pada modeling basis data relasional PostgreSQL, optimasi query indexing, dan keamanan data aplikasi.",
          avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
          skills: ["PostgreSQL", "Database Design", "Prisma ORM", "SQL Tuning"],
          githubUrl: "https://github.com",
          isManagement: false,
          orderIndex: 23,
        },
        {
          id: "m-24",
          name: "Wiryateja Pamungkas",
          nickname: "Teja",
          role: "Bendahara 2",
          department: "Finance & Asset Management",
          quote: "Ketelitian dalam angka menjamin kelancaran setiap proyek.",
          bio: "Bertanggung jawab atas pencatatan inventaris aset teknologi kelas, penganggaran logistik acara, dan asistensi keuangan tim.",
          avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=faces",
          skills: ["Asset Management", "Financial Audit", "Spreadsheets", "Logistics"],
          instagramUrl: "https://instagram.com",
          linkedinUrl: "https://linkedin.com",
          isManagement: true,
          orderIndex: 24,
        },
        {
          id: "m-25",
          name: "Zahira Khaizuran Al Kanza",
          nickname: "Zahira",
          role: "Sekretaris 1",
          department: "Administration & Documentation",
          quote: "Komunikasi tertulis yang jernih menyatukan seluruh visi tim.",
          bio: "Sekretaris 1 XI Internasional. Mengawal korespondensi resmi, penjadwalan agenda kelas, dan dokumentasi sentral portal web.",
          avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces",
          skills: ["Secretarial", "Public Communication", "Documentation", "Planning"],
          instagramUrl: "https://instagram.com",
          linkedinUrl: "https://linkedin.com",
          isManagement: true,
          orderIndex: 25,
        },
      ];

      for (const s of students) {
        await prisma.member.upsert({
          where: { id: s.id },
          update: s,
          create: s,
        });
      }

    // 5. Projects
    const projectCount = await prisma.project.count();
    if (projectCount === 0) {
      console.log("Seeding initial projects...");
      const projects = [
        {
          id: "p-1",
          title: "Simas — Smart Attendance Hub",
          slug: "simas-smart-attendance",
          tagline: "Platform presensi kelas berbasis geolokasi & QR token terenkripsi.",
          description: "Sistem presensi terpusat yang memudahkan wali kelas dan siswa mencatat kehadiran secara real-time dengan validasi radius GPS sekolah dan rotasi token otomatis setiap 30 detik.",
          category: "Web App",
          thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop",
          screenshots: [],
          techStack: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
          team: ["Radisty Dhisa Aqila", "Nabila Eka Khairunnisa"],
          featured: true,
          likes: 42,
          year: 2025,
          demoUrl: "https://internext.web.id/projects",
          githubUrl: "https://github.com",
        },
        {
          id: "p-2",
          title: "EduQuest — Interactive Learning LMS",
          slug: "eduquest-learning-lms",
          tagline: "Gamified learning management system untuk tugas dan kuis harian.",
          description: "Platform belajar interaktif yang mengintegrasikan leaderboard, achievement badges, dan modul latihan soal untuk meningkatkan partisipasi belajar kelompok di kelas.",
          category: "Web App",
          thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=500&fit=crop",
          screenshots: [],
          techStack: ["React", "TypeScript", "Node.js", "Tailwind CSS"],
          team: ["Bima Satria Nugraha", "Elang Dimas Syadewa"],
          featured: true,
          likes: 38,
          year: 2025,
          demoUrl: "https://internext.web.id/projects",
          githubUrl: "https://github.com",
        },
        {
          id: "p-3",
          title: "HydroSense — IoT Smart Farming",
          slug: "hydrosense-iot-smart-farming",
          tagline: "Pemantauan nutrisi hidroponik dan pH air berbasis sensor ESP32.",
          description: "Solusi otomatisasi kebun hidroponik sekolah dengan telemetry dashboard yang menampilkan metrik suhu air, PPM nutrisi, dan level cairan secara visual.",
          category: "IoT / Hardware",
          thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=500&fit=crop",
          screenshots: [],
          techStack: ["ESP32", "C++", "MQTT", "Next.js Dashboard"],
          team: ["Dimas Aditya Wardhana", "Muhammad Fadhil"],
          featured: true,
          likes: 56,
          year: 2025,
          demoUrl: "https://internext.web.id/projects",
          githubUrl: "https://github.com",
        },
        {
          id: "p-4",
          title: "EcoSort — AI Waste Identifier",
          slug: "ecosort-ai-waste-identifier",
          tagline: "Deteksi klasifikasi sampah otomatis menggunakan Computer Vision.",
          description: "Aplikasi cerdas untuk membantu pemilahan sampah anorganik dan organik di lingkungan sekolah dengan model klasifikasi gambar TensorFlow Lite.",
          category: "AI / Machine Learning",
          thumbnail: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&h=500&fit=crop",
          screenshots: [],
          techStack: ["Python", "TensorFlow", "FastAPI", "React Native"],
          team: ["Salsabila Maharani", "Rizky Pratama Putra"],
          featured: true,
          likes: 47,
          year: 2025,
          demoUrl: "https://internext.web.id/projects",
          githubUrl: "https://github.com",
        },
      ];

      for (const p of projects) {
        await prisma.project.upsert({
          where: { slug: p.slug },
          update: {},
          create: p,
        });
      }
    }

    // 6. Articles
    const articleCount = await prisma.article.count();
    if (articleCount === 0) {
      console.log("Seeding initial articles...");
      const articles = [
        {
          id: "a-1",
          title: "Juara 1 LKS Bidang Web Technologies: Dedikasi & Kolaborasi Tim",
          slug: "juara-1-lks-web-technologies",
          summary: "Perjalanan intensif perwakilan kelas dalam kompetisi keahlian tingkat provinsi hingga meraih podium tertinggi.",
          content: "Keberhasilan ini merupakan buah dari persiapan panjang selama enam bulan. Tim mendedikasikan waktu sepulang sekolah untuk memperdalam arsitektur web modern, optimasi performa, dan implementasi automated testing.\n\nDukungan penuh dari wali kelas dan teman-teman sekelas menjadi pilar moral terpenting di setiap tahap kompetisi.",
          category: "Prestasi",
          authorName: "Rafi Arya Pratama",
          authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces",
          authorRole: "Sekretaris & Editor",
          date: "2025-11-20",
          coverImage: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=1000&h=600&fit=crop",
          isPinned: true,
          readTime: "3 menit baca",
          tags: ["LKS", "Juara", "Web Tech", "Prestasi"],
        },
        {
          id: "a-2",
          title: "Kunjungan Industri & Tech Talk di Silicon Valley Jakarta Hub",
          slug: "kunjungan-industri-tech-talk-jakarta",
          summary: "Eksplorasi langsung kultur kerja tech unicorn, mendalami standar clean code dan observability bersama para senior software engineers.",
          content: "Rombongan kelas Internext berkesempatan melakukan kunjungan industri edukatif ke salah satu pusat inovasi teknologi terkemuka di Jakarta. Kegiatan ini bertujuan memperluas wawasan siswa terhadap lanskap industri perangkat lunak modern.\n\nSiswa diajak memahami pipeline deployment modern, monitoring microservices, dan berdiskusi langsung dengan tech leads mengenai jalur karier di bidang software engineering.",
          category: "Event",
          authorName: "Radisty Dhisa Aqila",
          authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=faces",
          authorRole: "Ketua Kelas",
          date: "2025-10-12",
          coverImage: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=1000&h=600&fit=crop",
          isPinned: false,
          readTime: "4 menit baca",
          tags: ["TechTalk", "Industri", "Edukasi"],
        },
        {
          id: "a-3",
          title: "Peluncuran Portal Resmi Internext.web.id Menuju Era Baru",
          slug: "peluncuran-portal-resmi-internext",
          summary: "Website resmi kelas resmi diluncurkan sebagai pusat identitas, dokumentasi kegiatan, dan showcase karya siswa berstandar industri.",
          content: "Setelah melalui proses perencanaan dan pengembangan bertahap, portal digital internext.web.id kini resmi beroperasi. Website ini dirancang sebagai wadah jangka panjang yang merekam seluruh perjalanan kelas.\n\nSetiap siswa memiliki profil pribadi, ruang showcase portofolio, dan dokumentasi momen yang dapat diakses oleh publik, guru, dan para alumni.",
          category: "Pengumuman",
          authorName: "Elang Dimas Syadewa",
          authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces",
          authorRole: "Wakil Ketua",
          date: "2025-09-01",
          coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1000&h=600&fit=crop",
          isPinned: false,
          readTime: "2 menit baca",
          tags: ["Peluncuran", "Portal", "Internext"],
        },
      ];

      for (const a of articles) {
        await prisma.article.upsert({
          where: { slug: a.slug },
          update: {},
          create: a,
        });
      }
    }

    // 7. Events
    const eventCount = await prisma.event.count();
    if (eventCount === 0) {
      console.log("Seeding initial events...");
      const events = [
        {
          id: "e-1",
          title: "Bootcamp Web Architecture & UI/UX Moklet 2026",
          description: "Sesi intensif pematangan arsitektur web modern, design token, dan integrasi API bagi seluruh siswa XI Internasional SMK Telkom Malang.",
          date: "2026-08-28T08:00:00+07:00",
          location: "Laboratorium Komputer 3, SMK Telkom Malang",
          committee: "Divisi IT & Riset Internext",
          category: "Akademik",
          status: "completed",
          countdownTarget: "2026-08-28T08:00:00+07:00",
          coverImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1000&h=600&fit=crop",
        },
        {
          id: "e-2",
          title: "Sprint Showcase & Review Portofolio Digital Kelas",
          description: "Agenda sinkronisasi karya 25 siswa, presentasi fitur showcase 360°, dan evaluasi kesiapan rilis platform digital angkatan bersama wali kelas.",
          date: "2026-09-16T09:00:00+07:00",
          location: "Ruang 34, SMK Telkom Malang",
          committee: "Pengurus Harian & Nahkoda Kelas",
          category: "Akademik",
          status: "ongoing",
          countdownTarget: "2026-09-16T09:00:00+07:00",
          coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&h=600&fit=crop",
        },
        {
          id: "e-3",
          title: "Moklet International Coding Camp & Hackathon",
          description: "Kompetisi hackathon dan kolaborasi lintas minat merancang solusi perangkat lunak berbasis AI dan IoT berstandar industri internasional.",
          date: "2026-10-12T08:30:00+07:00",
          location: "Auditorium Utama & Cloud Lab, SMK Telkom Malang",
          committee: "Tim Kolaborasi & Event Sekolah",
          category: "Akademik",
          status: "upcoming",
          countdownTarget: "2026-10-12T08:30:00+07:00",
          coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1000&h=600&fit=crop",
        },
        {
          id: "e-4",
          title: "Internext Tech Expo & Final Showcase 2026",
          description: "Pameran akbar karya inovasi teknologi kelas XI Internasional yang dihadiri oleh praktisi industri teknologi, alumni, dan dewan guru.",
          date: "2026-11-20T08:30:00+07:00",
          location: "Auditorium Utama Kampus Digital",
          committee: "Divisi Project & Event Internext",
          category: "Akademik",
          status: "upcoming",
          countdownTarget: "2026-11-20T08:30:00+07:00",
          coverImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1000&h=600&fit=crop",
        },
      ];

      for (const ev of events) {
        await prisma.event.upsert({
          where: { id: ev.id },
          update: {},
          create: ev,
        });
      }
    }

    // 8. Gallery & Kubah 3D
    const kubahCount = await prisma.gallery.count({ where: { album: "Kubah 3D" } });
    if (kubahCount === 0) {
      console.log("Seeding initial Kubah 3D gallery images...");
      const kubahGallery = [
        {
          id: "g-kubah-1",
          title: "Presentasi Karya Akhir Semester",
          type: "photo",
          url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-12-10",
          photographer: "Dokumentasi Kelas",
          caption: "Suasana sesi tanya jawab evaluasi proyek bersama dewan guru penguji.",
          likes: 45,
        },
        {
          id: "g-kubah-2",
          title: "Workshop UI/UX Design System",
          type: "photo",
          url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-10-05",
          photographer: "Dokumentasi Kelas",
          caption: "Kolaborasi merancang token visual dan atomic components di Figma.",
          likes: 38,
        },
        {
          id: "g-kubah-3",
          title: "Pekan Olahraga & Class Meeting",
          type: "photo",
          url: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-11-15",
          photographer: "Dokumentasi Kelas",
          caption: "Kemenangan tim futsal kelas pada turnamen tahunan sekolah.",
          likes: 52,
        },
        {
          id: "g-kubah-4",
          title: "Bakti Sosial & Santunan Masyarakat",
          type: "photo",
          url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-08-20",
          photographer: "Dokumentasi Kelas",
          caption: "Berbagi kebahagiaan dan sembako bersama warga di lingkungan sekitar sekolah.",
          likes: 67,
        },
        {
          id: "g-kubah-5",
          title: "Kolaborasi Tim & Coding Session",
          type: "photo",
          url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-09-12",
          photographer: "Dokumentasi Kelas",
          caption: "Eksplorasi pembuatan REST API terpusat bersama tim pengembang.",
          likes: 34,
        },
        {
          id: "g-kubah-6",
          title: "Diskusi Desain Produk Digital",
          type: "photo",
          url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-09-18",
          photographer: "Dokumentasi Kelas",
          caption: "Penyusunan user journey dan wireframing antarmuka web kelas.",
          likes: 41,
        },
        {
          id: "g-kubah-7",
          title: "Kebersamaan Angkatan Internext",
          type: "photo",
          url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-10-22",
          photographer: "Dokumentasi Kelas",
          caption: "Momen hangat kekeluargaan dan soliditas 25 siswa XI Internasional.",
          likes: 80,
        },
        {
          id: "g-kubah-8",
          title: "Brainstorming Sprint Mingguan",
          type: "photo",
          url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-11-04",
          photographer: "Dokumentasi Kelas",
          caption: "Penetapan prioritas backlog sprint di papan Kanban kelas.",
          likes: 29,
        },
        {
          id: "g-kubah-9",
          title: "Kelas Interaktif & Pemrograman",
          type: "photo",
          url: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-11-19",
          photographer: "Dokumentasi Kelas",
          caption: "Pembelajaran algoritma dan struktur data intensif di lab komputer.",
          likes: 37,
        },
        {
          id: "g-kubah-10",
          title: "Perayaan Kelulusan & Prestasi",
          type: "photo",
          url: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-12-01",
          photographer: "Dokumentasi Kelas",
          caption: "Syukuran pencapaian medali lomba kompetensi siswa tingkat provinsi.",
          likes: 62,
        },
        {
          id: "g-kubah-11",
          title: "Tech Expo & Inovasi Digital",
          type: "photo",
          url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2025-12-15",
          photographer: "Dokumentasi Kelas",
          caption: "Booth pameran karya aplikasi web dan IoT siswa di hadapan umum.",
          likes: 58,
        },
        {
          id: "g-kubah-12",
          title: "Ujian Sertifikasi Internasional",
          type: "photo",
          url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2026-01-10",
          photographer: "Dokumentasi Kelas",
          caption: "Sesi ujian sertifikasi kompetensi IT internasional.",
          likes: 49,
        },
        {
          id: "g-kubah-13",
          title: "Farewell Night & Graduation",
          type: "photo",
          url: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2026-01-25",
          photographer: "Dokumentasi Kelas",
          caption: "Malam keakraban angkatan dan refleksi perjalanan belajar.",
          likes: 73,
        },
        {
          id: "g-kubah-14",
          title: "Cyber Security Lab Session",
          type: "photo",
          url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2026-02-05",
          photographer: "Dokumentasi Kelas",
          caption: "Praktik simulasi network hardening dan deteksi intrusi di lab.",
          likes: 39,
        },
        {
          id: "g-kubah-15",
          title: "Virtual Reality Simulation Hub",
          type: "photo",
          url: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2026-02-14",
          photographer: "Dokumentasi Kelas",
          caption: "Eksperimen interaksi lingkungan virtual dan rendering 3D real-time.",
          likes: 51,
        },
        {
          id: "g-kubah-16",
          title: "Studio Musik & Sound Engineering",
          type: "photo",
          url: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=800&fit=crop",
          thumbnail: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=400&fit=crop",
          album: "Kubah 3D",
          date: "2026-02-20",
          photographer: "Dokumentasi Kelas",
          caption: "Produksi audio tema dan sound design untuk portofolio angkatan.",
          likes: 44,
        },
      ];

      for (const g of kubahGallery) {
        await prisma.gallery.upsert({
          where: { id: g.id },
          update: {},
          create: g,
        });
      }
    }

    console.log("✅ Seed runner finished successfully!");
  } catch (err) {
    console.error("Seed runner error:", err);
  } finally {
    await prisma.$disconnect();
  }
}

runSeed();
