import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting database seed for SMK Telkom Malang (XI Internasional)...");

  // 1. Class Profile
  await prisma.classProfile.upsert({
    where: { id: "default" },
    update: {
      name: "XI Internasional",
      school: "SMK Telkom Malang",
      generation: "Angkatan 2026",
      tagline: "Connected. Forward. Together.",
      description:
        "Pusat identitas, dokumentasi, komunikasi, showcase, dan portofolio kelas XI Internasional SMK Telkom Malang yang dibangun dengan standar produk digital modern.",
      homeroomTeacher: "Drs. Hendra Kusuma, M.Kom",
      classPresident: "Fakhri Ramadhan",
      vicePresident: "Alya Putri Nuraini",
      memberCount: 25,
      projectCount: 24,
      achievementCount: 15,
      eventCount: 18,
      labLocation: "Gedung TI & IoT Lab, SMK Telkom Malang, Jl. Danau Ranau, Sawojajar, Kota Malang",
      email: "contact@internext.web.id",
      instagram: "https://instagram.com/internext.class",
      github: "https://github.com/internext-class",
      youtube: "https://youtube.com/@internext",
      tiktok: "https://tiktok.com/@internext.class",
    },
    create: {
      id: "default",
      name: "XI Internasional",
      school: "SMK Telkom Malang",
      generation: "Angkatan 2026",
      tagline: "Connected. Forward. Together.",
      description:
        "Pusat identitas, dokumentasi, komunikasi, showcase, dan portofolio kelas XI Internasional SMK Telkom Malang yang dibangun dengan standar produk digital modern.",
      homeroomTeacher: "Drs. Hendra Kusuma, M.Kom",
      classPresident: "Fakhri Ramadhan",
      vicePresident: "Alya Putri Nuraini",
      memberCount: 25,
      projectCount: 24,
      achievementCount: 15,
      eventCount: 18,
      labLocation: "Gedung TI & IoT Lab, SMK Telkom Malang, Jl. Danau Ranau, Sawojajar, Kota Malang",
      email: "contact@internext.web.id",
      instagram: "https://instagram.com/internext.class",
      github: "https://github.com/internext-class",
      youtube: "https://youtube.com/@internext",
      tiktok: "https://tiktok.com/@internext.class",
    },
  });

  // 2. Chat Channels
  const channels = [
    {
      id: "apresiasi-publik",
      name: "apresiasi-publik",
      title: "Kanal Apresiasi & Buku Tamu",
      topic: "Ruang apresiasi, doa, dan motivasi bagi siswa XI Internasional SMK Telkom Malang. Bot menyambut setiap ucapan hangat!",
      badge: "Utama",
      orderIndex: 0,
    },
    {
      id: "ngobrol-santai",
      name: "ngobrol-santai",
      title: "Obrolan Santai Siswa & Tamu",
      topic: "Kanal obrolan bebas antar siswa, alumni, dan teman-teman tanpa bot. Mengalir bebas untuk berdiskusi santai!",
      badge: "Komunitas",
      orderIndex: 1,
    },
    {
      id: "tanya-pengurus",
      name: "tanya-pengurus",
      title: "Tanya & Kontak Pengurus",
      topic: "Saluran komunikasi langsung dengan ketua kelas, wali kelas, dan tim pengurus XI Internasional.",
      badge: "Resmi",
      orderIndex: 2,
    },
    {
      id: "kolaborasi-proyek",
      name: "kolaborasi-proyek",
      title: "Kolaborasi & Ide Tech",
      topic: "Eksplorasi ide aplikasi, open source, persiapan LKS, dan kerja sama teknologi bareng siswa Moklet.",
      badge: "Tech",
      orderIndex: 3,
    },
  ];

  for (const ch of channels) {
    await prisma.chatChannel.upsert({
      where: { id: ch.id },
      update: ch,
      create: ch,
    });
  }

  // 3. Members (25 Students of XI Internasional - SMK Telkom Malang)
  const students = [
    {
      id: "m-1",
      name: "Fakhri Ramadhan",
      nickname: "Fakhri",
      role: "Ketua Kelas",
      department: "Executive & Project Management",
      quote: "Membangun masa depan bukan tentang menunggu, tapi mengeksekusi.",
      bio: "Ketua kelas XI Internasional SMK Telkom Malang. Tech enthusiast dengan fokus pada Fullstack Next.js dan agile leadership.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
      skills: ["TypeScript", "Next.js", "Team Leadership", "Product Management"],
      githubUrl: "https://github.com",
      linkedinUrl: "https://linkedin.com",
      instagramUrl: "https://instagram.com",
      isManagement: true,
      orderIndex: 1,
    },
    {
      id: "m-2",
      name: "Alya Putri Nuraini",
      nickname: "Alya",
      role: "Wakil Ketua",
      department: "Operations & Community",
      quote: "Kreativitas dan disiplin adalah dua sisi dari koin yang sama.",
      bio: "UI/UX Designer yang berorientasi pada riset pengguna dan desain sistem kelas. Bertanggung jawab atas koordinasi operasional tim.",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=faces",
      skills: ["Figma", "Design Systems", "User Research", "Tailwind CSS"],
      instagramUrl: "https://instagram.com",
      linkedinUrl: "https://linkedin.com",
      isManagement: true,
      orderIndex: 2,
    },
    {
      id: "m-3",
      name: "Rafi Arya Pratama",
      nickname: "Rafi",
      role: "Sekretaris",
      department: "Documentation & Content",
      quote: "Dokumentasi yang rapi adalah cerminan dari arsitektur yang kokoh.",
      bio: "Menjaga keteraturan log proyek, arsip keputusan teknis, dan manajemen konten publikasi kelas XI Internasional.",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces",
      skills: ["Technical Writing", "Markdown", "Git", "Content Strategy"],
      githubUrl: "https://github.com",
      isManagement: true,
      orderIndex: 3,
    },
    {
      id: "m-4",
      name: "Zahra Salsabila",
      nickname: "Zahra",
      role: "Bendahara",
      department: "Finance & Logistics",
      quote: "Transparansi dan ketelitian melahirkan rasa saling percaya.",
      bio: "Mengelola transparansi kas kelas, pendanaan kegiatan, dan perencanaan budget project bersama.",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=faces",
      skills: ["Budgeting", "Data Analysis", "Spreadsheet", "Project Estimation"],
      instagramUrl: "https://instagram.com",
      isManagement: true,
      orderIndex: 4,
    },
    {
      id: "m-5",
      name: "Bima Satria Nugraha",
      nickname: "Bima",
      role: "Divisi IT & Riset",
      department: "Frontend Engineering",
      quote: "Pixel-perfect adalah standar minimal, bukan tujuan akhir.",
      bio: "Spesialis animasi UI modern, micro-interactions, 3D WebGL, dan Web Performance Optimization.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces",
      skills: ["React", "Tailwind CSS", "GSAP", "Three.js"],
      githubUrl: "https://github.com",
      isManagement: true,
      orderIndex: 5,
    },
    {
      id: "m-6",
      name: "Nabila Eka Khairunnisa",
      nickname: "Nabila",
      role: "Divisi Media & Humas",
      department: "Backend & Systems",
      quote: "Arsitektur yang baik tidak terlihat sampai ada masalah.",
      bio: "Pengembang sistem backend berbasis Node.js dan PostgreSQL dengan ketertarikan tinggi pada distributed systems dan API design.",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces",
      skills: ["NestJS", "PostgreSQL", "Docker", "REST API"],
      githubUrl: "https://github.com",
      isManagement: true,
      orderIndex: 6,
    },
    {
      id: "m-7",
      name: "Dimas Aditya Wardhana",
      nickname: "Dimas",
      role: "Anggota",
      department: "DevOps & Infrastructure",
      quote: "Automate everything, monitor continuously.",
      bio: "Fokus pada CI/CD pipelines, container orchestration, Linux systems, dan cloud deployment Coolify.",
      avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=faces",
      skills: ["Linux", "Docker", "GitHub Actions", "Nginx"],
      githubUrl: "https://github.com",
      isManagement: false,
      orderIndex: 7,
    },
    {
      id: "m-8",
      name: "Tiara Anindya Putri",
      nickname: "Tiara",
      role: "Anggota",
      department: "UI/UX & Mobile",
      quote: "Design is not just what it looks like, it is how it works.",
      bio: "Mobile app enthusiast mengembangkan antarmuka ramah pengguna dengan Flutter dan React Native.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
      skills: ["Flutter", "Figma", "Mobile UI", "Prototyping"],
      isManagement: false,
      orderIndex: 8,
    },
    {
      id: "m-9",
      name: "Rizky Pratama Putra",
      nickname: "Rizky",
      role: "Anggota",
      department: "Cyber Security & Networks",
      quote: "Security is a process, not a product.",
      bio: "Mendalami network pentesting, secure coding, dan implementasi zero-trust security.",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
      skills: ["Network Security", "Linux", "Python", "Wireshark"],
      isManagement: false,
      orderIndex: 9,
    },
    {
      id: "m-10",
      name: "Salsabila Maharani",
      nickname: "Salsa",
      role: "Anggota",
      department: "Data Science & AI",
      quote: "In God we trust, all others must bring data.",
      bio: "Mengeksplorasi LLM, machine learning, dan visualisasi data interaktif untuk problem solving sekolah.",
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=faces",
      skills: ["Python", "Pandas", "Scikit-Learn", "FastAPI"],
      isManagement: false,
      orderIndex: 10,
    },
    {
      id: "m-11",
      name: "Arya Wijaya Kusuma",
      nickname: "Arya",
      role: "Anggota",
      department: "Game Development & 3D",
      quote: "Games are the interactive canvas of modern imagination.",
      bio: "Spesialis gameplay programming di Godot dan Unity serta modeling asset 3D di Blender.",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=faces",
      skills: ["Godot", "C#", "Blender", "Shaders"],
      isManagement: false,
      orderIndex: 11,
    },
    {
      id: "m-12",
      name: "Jessica Evelyn Tan",
      nickname: "Jessica",
      role: "Anggota",
      department: "Fullstack Web",
      quote: "Ship early, iterate fast, listen to users.",
      bio: "Pengembang solusi web berbasis TypeScript, Tailwind, dan Next.js dengan fokus pada clean architecture.",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces",
      skills: ["React", "TypeScript", "Prisma", "PostgreSQL"],
      isManagement: false,
      orderIndex: 12,
    },
    {
      id: "m-13",
      name: "Muhammad Fadhil",
      nickname: "Fadhil",
      role: "Anggota",
      department: "Embedded Systems & IoT",
      quote: "Connecting the physical and digital world seamlessly.",
      bio: "Menghubungkan mikrokontroler ESP32, sensor cerdas, dan dashboard analitik berbasis cloud.",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&crop=faces",
      skills: ["C++", "ESP32", "MQTT", "Arduino"],
      isManagement: false,
      orderIndex: 13,
    },
    {
      id: "m-14",
      name: "Amanda Kirana",
      nickname: "Amanda",
      role: "Anggota",
      department: "Creative Design & Motion",
      quote: "Great design makes the complex feel effortlessly simple.",
      bio: "Menciptakan motion graphic, teaser video kegiatan, dan visual branding kelas.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces",
      skills: ["After Effects", "Illustrator", "Motion Graphic", "Branding"],
      isManagement: false,
      orderIndex: 14,
    },
    {
      id: "m-15",
      name: "Bagas Putra Perkasa",
      nickname: "Bagas",
      role: "Anggota",
      department: "Backend & Microservices",
      quote: "Scalability begins at the first line of code.",
      bio: "Membangun microservices tangguh dengan Go dan Redis untuk high-throughput handling.",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
      skills: ["Golang", "Redis", "Docker", "PostgreSQL"],
      isManagement: false,
      orderIndex: 15,
    },
    {
      id: "m-16",
      name: "Clarissa Aurelia",
      nickname: "Clarissa",
      role: "Anggota",
      department: "Product Research & Strategy",
      quote: "Fall in love with the problem, not the solution.",
      bio: "Riset kebutuhan siswa dan merancang alur pengalaman digital terintegrasi di lingkungan sekolah.",
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=faces",
      skills: ["Product Management", "User Journey", "Analytics", "Wireframing"],
      isManagement: false,
      orderIndex: 16,
    },
    {
      id: "m-17",
      name: "Daffa Al-Ghifari",
      nickname: "Daffa",
      role: "Anggota",
      department: "QA & Automated Testing",
      quote: "Quality is not an act, it is a habit.",
      bio: "Membangun unit testing, end-to-end testing di Playwright, dan standardisasi kualitas kode tim.",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=faces",
      skills: ["Playwright", "Jest", "CI Testing", "Debugging"],
      isManagement: false,
      orderIndex: 17,
    },
    {
      id: "m-18",
      name: "Ezza Novalino",
      nickname: "Ezza",
      role: "Anggota",
      department: "Cloud Architecture",
      quote: "Resilience over perfection in modern architecture.",
      bio: "Eksplorasi cloud providers, serverless computing, dan arsitektur database modern.",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&crop=faces",
      skills: ["AWS", "Terraform", "Serverless", "PostgreSQL"],
      isManagement: false,
      orderIndex: 18,
    },
    {
      id: "m-19",
      name: "Farhan Maulana",
      nickname: "Farhan",
      role: "Anggota",
      department: "Frontend & Performance",
      quote: "Speed is the best feature any application can have.",
      bio: "Fokus pada optimasi Core Web Vitals, SSR caching, dan rendering arsitektur Next.js.",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces",
      skills: ["Next.js", "Lighthouse", "TypeScript", "Performance"],
      isManagement: false,
      orderIndex: 19,
    },
    {
      id: "m-20",
      name: "Gita Permata",
      nickname: "Gita",
      role: "Anggota",
      department: "Technical Writing & Branding",
      quote: "Code without words is a story without a voice.",
      bio: "Menyusun dokumentasi API yang jelas, blog teknis, dan rilis warta kegiatan kelas.",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=faces",
      skills: ["Tech Writing", "Copywriting", "SEO", "Markdown"],
      isManagement: false,
      orderIndex: 20,
    },
    {
      id: "m-21",
      name: "Haikal Rasyid",
      nickname: "Haikal",
      role: "Anggota",
      department: "Mobile Engineering",
      quote: "Every tap should feel instant and delightful.",
      bio: "Pengembang aplikasi multiplatform berorientasi performa tinggi dan animasi transisi halus.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces",
      skills: ["Flutter", "Dart", "Firebase", "State Management"],
      isManagement: false,
      orderIndex: 21,
    },
    {
      id: "m-22",
      name: "Indah Cahyani",
      nickname: "Indah",
      role: "Anggota",
      department: "UI Interaction Design",
      quote: "Micro-interactions turn software into magic.",
      bio: "Merancang gesture animations, scroll reveals, dan glassmorphism components.",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=faces",
      skills: ["Figma", "CSS Animations", "Framer Motion", "Design"],
      isManagement: false,
      orderIndex: 22,
    },
    {
      id: "m-23",
      name: "Jonathan Adrian",
      nickname: "Jonathan",
      role: "Anggota",
      department: "System Administration",
      quote: "Uptime is not just a metric, it is our pride.",
      bio: "Pengelolaan server homelab sekolah, reverse proxy Nginx, dan backup otomatis berkala.",
      avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=faces",
      skills: ["Linux Server", "Nginx", "Bash", "Networking"],
      isManagement: false,
      orderIndex: 23,
    },
    {
      id: "m-24",
      name: "Karina Larasati",
      nickname: "Karina",
      role: "Anggota",
      department: "Emerging Tech & Web3",
      quote: "Decentralized systems empower the next generation.",
      bio: "Riset smart contracts, decentralized identity, dan integrasi wallet authentication.",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces",
      skills: ["Solidity", "Ethers.js", "Web3", "JavaScript"],
      isManagement: false,
      orderIndex: 24,
    },
    {
      id: "m-25",
      name: "Kevin Sanjaya",
      nickname: "Kevin",
      role: "Anggota",
      department: "Fullstack Engineering",
      quote: "Write code that the next engineer will love to read.",
      bio: "Membangun sistem integrasi backend-frontend modern dengan Next.js App Router dan GraphQL/REST.",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
      skills: ["Node.js", "React", "PostgreSQL", "Tailwind CSS"],
      isManagement: false,
      orderIndex: 25,
    },
  ];

  for (const s of students) {
    await prisma.member.upsert({
      where: { id: s.id },
      update: s,
      create: s,
    });
  }

  // 4. Initial Chat Messages
  const initialChat = [
    {
      id: "chat-apresiasi-1",
      channelId: "apresiasi-publik",
      name: "Drs. Hendra Kusuma, M.Kom",
      role: "Guru",
      message: "Bangga melihat dedikasi dan karya hebat anak-anak XI Internasional SMK Telkom Malang. Teruslah berkarya dan jadilah engineer berintegritas tinggi!",
      timestamp: "10 Feb 2026, 10:00",
      reactions: [{ emoji: "❤️", count: 24, userReacted: false }, { emoji: "👏", count: 16, userReacted: false }],
    },
    {
      id: "chat-apresiasi-2",
      channelId: "apresiasi-publik",
      name: "Kevin Pratama, S.Kom (Alumni Moklet)",
      role: "Alumni",
      message: "Website kelasnya luar biasa keren! Nuansa dark mode dan portofolio 360-nya serasa tech startup silicon valley. Keren banget adik-adik XI Internasional!",
      timestamp: "14 Feb 2026, 14:30",
      reactions: [{ emoji: "🔥", count: 19, userReacted: false }, { emoji: "🚀", count: 11, userReacted: false }],
    },
    {
      id: "chat-santai-1",
      channelId: "ngobrol-santai",
      name: "Fakhri Ramadhan",
      role: "Siswa",
      message: "Halo semuanya! Selamat datang di kanal ngobrol santai XI Internasional. Di sini bebas ngobrol santai seputar projek, sharing ilmu, atau sekadar sapa-sapaan! ☕👋",
      timestamp: "Hari ini, 09:00",
      reactions: [{ emoji: "🚀", count: 8, userReacted: false }],
    },
  ];

  for (const m of initialChat) {
    await prisma.chatMessage.upsert({
      where: { id: m.id },
      update: m,
      create: m,
    });
  }

  console.log("✅ Seed completed successfully for 25 students of XI Internasional SMK Telkom Malang!");
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
