export const siteConfig = {
  name: "Internext",
  domain: "internext.web.id",
  tagline: "Connected. Forward. Together.",
  description:
    "Pusat identitas, dokumentasi, komunikasi, showcase, dan portofolio kelas yang dibangun dengan standar produk digital modern.",
  classInfo: {
    name: "XI Internasional",
    generation: "Angkatan 2026",
    school: "SMK Telkom Malang",
    homeroomTeacher: "Andree Rivan Kurniawan, M.Pd",
    classPresident: "Radisty Dhisa Aqila",
    vicePresident: "Elang Dimas Syadewa",
    memberCount: 25,
    projectCount: 24,
    achievementCount: 15,
    eventCount: 18,
    labLocation: "Ruang 34, SMK Telkom Malang, Jl. Danau Ranau, Sawojajar, Kota Malang",
    graduationDate: "2026-06-15T09:00:00+07:00",
  },
  navLinks: [
    { label: "Beranda", href: "/" },
    { label: "Tentang", href: "/about" },
    { label: "Anggota", href: "/members" },
    { label: "Karya", href: "/projects" },
    { label: "Berita", href: "/news" },
    { label: "Agenda", href: "/events" },
    { label: "Galeri", href: "/gallery" },
    { label: "Buku Tamu", href: "/contact" },
  ],
  socials: {
    instagram: "https://instagram.com/internext.class",
    github: "https://github.com/internext-class",
    youtube: "https://youtube.com/@internext",
    tiktok: "https://tiktok.com/@internext.class",
    email: "contact@internext.web.id",
  },
};
